#!/bin/sh

BASEDIR=`dirname $0`

pushd $BASEDIR > /dev/null

/opt/helixutils/create-git-changelog --package=helixbilling --dir=$BASEDIR
dpkg-buildpackage -uc -us -b -rfakeroot
mkdir -p dist
mv ../helixbilling*.deb dist
rm -f  ../helixbilling*.changes

popd > /dev/null

