#!/bin/sh

set -e
#set -x

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

    rm -f /etc/nginx/sites-enabled/python-helixbilling
    rm -f /etc/supervisor/process-enabled/python-helixbilling.ini

    if [ "$1" = "purge" ]; then
        rm -f  /etc/nginx/sites-available/python-helixbilling
        rm -rf /etc/nginx/sites-available/python-hilixbilling-ssl/
        rm -f /etc/supervisor/process-available/python-helixbilling.ini
    fi

    if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
        db_version 2.0

        if [ -f /usr/share/dbconfig-common/dpkg/postrm.pgsql  ]; then
        	. /usr/share/dbconfig-common/dpkg/postrm.pgsql 
            dbc_go python-helixbilling $@
        fi
    fi
fi

CFG="/usr/share/python-support/python-helixbilling/helixbilling/conf/settings.py"
if [ -f $CFG ]; then
    rm -f $CFG
    if which ucf >/dev/null 2>&1; then
        ucf --debconf-ok --purge $CFG
    fi
fi

#DEBHELPER#
