_ = lambda x: x

# common codes
HELIXBILLING_ERROR = _('HELIXBILLING_ERROR')
HELIXBILLING_OBJECT_NOT_FOUND = _('HELIXBILLING_OBJECT_NOT_FOUND')
HELIXBILLING_OBJECT_ALREADY_EXISTS = _('HELIXBILLING_OBJECT_ALREADY_EXISTS')

# balance errors
HELIXBILLING_BALANCE_NOT_FOUND = _('HELIXBILLING_BALANCE_NOT_FOUND')
HELIXBILLING_BALANCE_ALREADY_EXISTS = _('HELIXBILLING_BALANCE_ALREADY_EXISTS')
HELIXBILLING_BALANCE_DISABLED = _('HELIXBILLING_BALANCE_DISABLED')
HELIXBILLING_MONEY_NOT_ENOUGH = _('HELIXBILLING_MONEY_NOT_ENOUGH')

# user errors
HELIXBILLING_USER_NOT_EXISTS = _('HELIXBILLING_USER_NOT_EXISTS')
HELIXBILLING_USER_CHECKING_ERROR = _('HELIXBILLING_USER_CHECKING_ERROR')