_ = lambda x: x

# common codes
HELIXBILLING_ERROR = _('HELIXBILLING_ERROR')
HELIXBILLING_OBJECT_NOT_FOUND = _('HELIXBILLING_OBJECT_NOT_FOUND')
HELIXBILLING_OBJECT_ALREADY_EXISTS = _('HELIXBILLING_OBJECT_ALREADY_EXISTS')
